Task 03

In [1]:
import numpy as np

# 1. Creating 1D Arrays
dataA = np.array([5, 10, 15, 20, 25])
dataB = np.array([2, 4, 6, 8, 10])
print("1. dataA:", dataA)
print("2. dataB:", dataB)

# 2. Creating a 2D Array
matrix = np.array([[3, 6], [9, 12]])
print("3. 2D Matrix:\n", matrix)

# 3. Shape and Size
print("4. Shape of matrix:", matrix.shape)
print("5. Size of dataA:", dataA.size)

# 4. Reshape
reshaped = dataA.reshape((5, 1))
print("6. Reshaped dataA to (5,1):\n", reshaped)

# 5. Indexing
print("7. Element at matrix[1,1]:", matrix[1, 1])

# 6. Slicing
print("8. First three elements of dataB:", dataB[:3])

# 7. Element-wise Addition
print("9. dataA + dataB =", dataA + dataB)

# 8. Element-wise Multiplication
print("10. dataA * dataB =", dataA * dataB)

# 9. Scalar Operation
print("11. dataA + 100 =", dataA + 100)

# 10. Aggregations
print("12. Sum of dataA:", np.sum(dataA))
print("13. Mean of dataB:", np.mean(dataB))
print("14. Median of dataA:", np.median(dataA))
print("15. Standard Deviation of dataA:", np.std(dataA))

# 11. Sorting
print("16. Sorted dataB:", np.sort(dataB))

# 12. Transposing a Matrix
print("17. Transposed matrix:\n", matrix.T)

# 13. Creating Special Arrays
zeros_arr = np.zeros((2, 3))
print("18. Zeros array (2x3):\n", zeros_arr)

identity_matrix = np.eye(4)
print("19. Identity matrix (4x4):\n", identity_matrix)

# 14. Creating Arrays using arange
range_array = np.arange(1, 11, 2)
print("20. Range array (1 to 10 step 2):", range_array)

# 15. Logical Filtering
filtered = dataA[dataA > 10]
print("21. Elements in dataA > 10:", filtered)




1. dataA: [ 5 10 15 20 25]
2. dataB: [ 2  4  6  8 10]
3. 2D Matrix:
 [[ 3  6]
 [ 9 12]]
4. Shape of matrix: (2, 2)
5. Size of dataA: 5
6. Reshaped dataA to (5,1):
 [[ 5]
 [10]
 [15]
 [20]
 [25]]
7. Element at matrix[1,1]: 12
8. First three elements of dataB: [2 4 6]
9. dataA + dataB = [ 7 14 21 28 35]
10. dataA * dataB = [ 10  40  90 160 250]
11. dataA + 100 = [105 110 115 120 125]
12. Sum of dataA: 75
13. Mean of dataB: 6.0
14. Median of dataA: 15.0
15. Standard Deviation of dataA: 7.0710678118654755
16. Sorted dataB: [ 2  4  6  8 10]
17. Transposed matrix:
 [[ 3  9]
 [ 6 12]]
18. Zeros array (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]
19. Identity matrix (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
20. Range array (1 to 10 step 2): [1 3 5 7 9]
21. Elements in dataA > 10: [15 20 25]
